package com.rnd.task.util;

public interface LTMSqlQueries {

	String SELECT_TASK_TYPE = "SELECT LTM_ATTRIBUTES.ID, ATTRIBUTE_TYPE,UI_KEY,DB_COLUMN,UI_LABEL ,DATA_TYPE ,DATA_LENGTH,LTM_ATTRIBUTES.CREATED_BY,LTM_ATTRIBUTES.CREATED_TIMESTAMP\r\n" + 
			"FROM LTM_ATTRIBUTES \r\n" + 
			"INNER JOIN LTM_TASK_TYPE_ATTR_MAP ON LTM_ATTRIBUTES.ID = LTM_TASK_TYPE_ATTR_MAP.ATTRIBUTE_ID \r\n" + 
			"INNER JOIN LTM_TASK_TYPE_METADATA ON LTM_TASK_TYPE_ATTR_MAP.TASKTYPE_ID = LTM_TASK_TYPE_METADATA.ID\r\n" + 
			"WHERE LTM_TASK_TYPE_METADATA.NAME = ? UNION ALL \r\n" + 
			"SELECT LTM_ATTRIBUTES.ID, ATTRIBUTE_TYPE,UI_KEY,DB_COLUMN ,UI_LABEL ,DATA_TYPE,DATA_LENGTH ,LTM_ATTRIBUTES.CREATED_BY,LTM_ATTRIBUTES.CREATED_TIMESTAMP \r\n" + 
			"FROM LTM.LTM_ATTRIBUTES WHERE ATTRIBUTE_TYPE IN('T','H')\r\n" + 
			"AND EXISTS (SELECT LTM_TASK_TYPE_METADATA.NAME FROM LTM_TASK_TYPE_METADATA WHERE LTM_TASK_TYPE_METADATA.NAME = ?)";
	String GET_ATTRIBUTE_SQL = "SELECT ID, ATTRIBUTE_TYPE,UI_KEY,DB_COLUMN,UI_LABEL ,DATA_TYPE ,DATA_LENGTH, CREATED_BY, CREATED_TIMESTAMP FROM LTM_ATTRIBUTES";
	
	String CREATE_SQL = "insert into LTM_TASK(ID,TASK_ID,TASK_TYPE,TASK_STATUS,CREATED_TIMESTAMP,CREATED_USERID,ACTION_MENU {FIELDS}) "
			+ "values(LTM_TASK_SEQ.NEXTVAL,?,?,?,?,?,?{WILDCARD})";
	
	String CREATE_MENDATE_SQL = "insert into LTM_TASK(ID,TASK_ID,TASK_TYPE,TASK_STATUS,CREATED_TIMESTAMP,CREATED_USERID,ACTION_MENU) "
			+ "values(LTM_TASK_SEQ.NEXTVAL,?,?,?,?,?,?)";

}
